/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signOut = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruble = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nightMode = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightArrows = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editAccount = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData events = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData changeLanguage = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addUser = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dateTimeCalendar = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftArrows = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followOn = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData publicationCalendar = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunny = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteUser = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blockUser = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribeUser = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData requestUser = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followOff = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happyEmoji = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sadEmoji = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
